apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-ybdh
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0038-tenant/tkrw-pr712-0075-0038-app/devfile-sample-ybdh@sha256:52b55d00de0cc46f3561e0aec3fb9918c5a2c936352764cc63cdeca682c102f0
        name: my-nodejs
        resources: {}
status: {}
